version: "3.3"
services:

  orthanc-viewer:
    build: server
    ports: ["8000:8042","2000:4242"]
    container_name: orthanc-viewer
    hostname: orthanc-viewer

    volumes:
        - ./server/orthanc.json:/etc/orthanc/orthanc.json
        - ./server/router.py:/python/router.py
    environment:
      ORTHANC__NAME: "orthanc-viewer"

      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__PYTHON_SCRIPT: "/python/router.py"
      ORTHANC__PYTHON_VERBOSE: "true"
    networks:
      - orthanc_net

  nginx:
    image: nginx:latest
    container_name: orthanc-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - orthanc-viewer
    networks:
      - orthanc_net

  orthanc-ai:
    build: AI_inference
    ports: ["8001:8042","2001:4242"]
    container_name: orthanc-ai
    hostname: orthanc-ai

    volumes:
        - ./AI_inference/orthanc.json:/etc/orthanc/orthanc.json
        - ./AI_inference/server.py:/python/server.py
    environment:
      ORTHANC__NAME: "orthanc-ai"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__PYTHON_SCRIPT: "/python/server.py"
      ORTHANC__PYTHON_VERBOSE: "true"
      AI_TEXT: "PROCESSED BY AI"
      AI_COLOR: "red"
      AI_NAME: "Red AI Model"
    networks:
      - orthanc_net

  orthanc-ai-green:
    build: AI_inference
    ports: ["8002:8042","2002:4242"]
    container_name: orthanc-ai-green
    hostname: orthanc-ai-green

    volumes:
        - ./AI_inference/orthanc.json:/etc/orthanc/orthanc.json
        - ./AI_inference/server.py:/python/server.py
    environment:
      ORTHANC__NAME: "orthanc-ai-green"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__PYTHON_SCRIPT: "/python/server.py"
      ORTHANC__PYTHON_VERBOSE: "true"
      AI_TEXT: "PROCESSED BY GREEN AI"
      AI_COLOR: "green"
      AI_NAME: "Green AI Model"
    networks:
      - orthanc_net

networks:
  orthanc_net:
    driver: bridge
